FROM gradle:8.6-jdk17 AS build
WORKDIR /workspace

COPY . .

RUN gradle build -x test

FROM eclipse-temurin:17-jdk
WORKDIR /app
COPY --from=build /workspace/build/libs/*.jar app.jar

EXPOSE 8080

CMD ["java", "-jar", "app.jar"] 